version: 2
updates:
  # Mantener actualizadas las dependencias de npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"

  # Mantener actualizadas las dependencias de GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci(deps)"
      prefix-development: "ci(deps-dev)"

  # Mantener actualizadas las dependencias de Devcontainers (Entornos de desarrollo)
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
