# Plataformas soportadas para el modelo de patrocinio (Funding)

# Tu usuario de GitHub Sponsors
github: [alvar3zjos3]

# Tu enlace personalizado para donaciones por PayPal
custom: ["https://www.paypal.me/alvarezjos3"]
