# Días de inactividad antes de marcar un issue/PR como inactivo
daysUntilStale: 30

# Días de inactividad antes de cerrar un issue/PR inactivo
daysUntilClose: 7

# Issues y PRs con estas etiquetas nunca se considerarán inactivos
exemptLabels:
  - feature
  - enhancement
  - help wanted
  - bug

# Etiqueta que se añadirá al marcar un issue/PR como inactivo
staleLabel: inactivo

# Comentario que dejará el bot al marcarlo como inactivo
markComment: >
  Este issue ha sido marcado automáticamente como inactivo por falta de
  actividad reciente. Si no hay nuevas respuestas o actualizaciones en los
  próximos 7 días, 
  se cerrará automáticamente. ¡Gracias por tus contribuciones!

# Comentario al cerrar un issue inactivo. (false = se cierra sin comentario adicional)
closeComment: false
