# Días de inactividad antes de marcar un issue como obsoleto
daysUntilStale: 30
# Días de inactividad antes de cerrar un issue obsoleto
daysUntilClose: 7
# Issues con estas etiquetas nunca se considerarán obsoletos
exemptLabels:
  - feature
  - enhancement
  - help wanted
  - bug

# Etiqueta al marcar un issue como obsoleto
staleLabel: stale
# Comentario al marcar un issue como obsoleto. Usa `false` para desactivarlo
markComment: >
  Este issue se ha marcado automáticamente como obsoleto por falta de actividad
  reciente. Se cerrará si no hay más actividad. Gracias por tus contribuciones.
# Comentario al cerrar un issue obsoleto. Usa `false` para desactivarlo
closeComment: false
