blank_issues_enabled: true
contact_links:
  - name: Pregunta
    url: https://github.com/alvar3zjos3/dev-readme-stats/discussions
    about: Haz y responde preguntas aquí.
  - name: Error
    url: https://github.com/alvar3zjos3/dev-readme-stats/issues/1772
    about:
      Antes de abrir un reporte de error, revisa el issue de códigos de error
      comunes.
  - name: Preguntas frecuentes
    url: https://github.com/alvar3zjos3/dev-readme-stats/discussions/1770
    about: Consulta primero las preguntas frecuentes antes de preguntar.
