name: Solicitud de función
description: Sugiere una idea para este proyecto.
labels:
  - "enhancement"
body:
  - type: textarea
    attributes:
      label: ¿Tu solicitud está relacionada con un problema? Descríbelo.
      description:
        Una descripción clara y concisa del problema. Ej. Me frustra cuando
        [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe la solución que te gustaría
      description: Una descripción clara y concisa de lo que quieres que ocurra.
  - type: textarea
    attributes:
      label: Describe alternativas que hayas considerado
      description:
        Una descripción clara y concisa de otras soluciones o funciones que
        hayas evaluado.
  - type: textarea
    attributes:
      label: Contexto adicional
      description:
        Cualquier otro contexto o capturas sobre la solicitud de función.
