name: Preparación de despliegue
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  config:
    if: github.repository == 'alvar3zjos3/dev-readme-stats'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Preparación de despliegue
        run: python ./.github/workflows/deploy-prep.py
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          branch: vercel
          create_branch: true
          push_options: "--force"
