name: Pruebas
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  build:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configurar Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Instalar y probar
        run: |
          npm ci
          npm run test

      - name: Ejecutar ESLint
        run: |
          npm run lint

      - name: Ejecutar pruebas de rendimiento
        run: |
          npm run bench

      - name: Ejecutar Prettier
        run: |
          npm run format:check

      - name: Cobertura de código
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
