name: Cerrar pull requests de temas obsoletos

on:
  - pull_request_target

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  close-prs:
    if: github.repository == 'alvar3zjos3/dev-readme-stats'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Check out the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Close Pull Requests
        run: |
          comment_message="We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/alvar3zjos3/dev-readme-stats?tab=readme-ov-file#customization)."

          for pr_number in $(gh pr list -l "themes" -q is:open --json number -q ".[].number"); do
            gh pr close $pr_number -c "$comment_message"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
